#pragma once

#include "expressions/expression.h"
#include "expressions/terminal/coord_expression.h"
#include "expressions/terminal/number_expression.h"
#include "expressions/terminal/string_expression.h"
#include "expressions/nonterminal/configure_path.h"
#include "expressions/terminal/clear_expression.h"
#include "expressions/terminal/quit_expression.h"
#include "expressions/terminal/view_configs.h"
#include "expressions/nonterminal/add_profile.h"
#include "expressions/terminal/view_profiles_expression.h"
#include "expressions/nonterminal/view_profile_expression.h"
#include "expressions/nonterminal/analyze_expression.h"
#include "expressions/nonterminal/remove_profile_expression.h"

#include "token.h"

#include <vector>
#include <string>
#include <stdexcept>

/**
 * @class Parser
 * @brief A recursive descent parser that constructs an Abstract Syntax Tree (AST) from a sequence of tokens.
 * 
 * The Parser takes a sequence of lexical tokens generated by the Lexer and evaluates them 
 * against the grammar rules of the application's CLI. It builds a linked chain of 
 * Expression nodes (the AST) that can subsequently be executed by the application context.
 */
class Parser {
    private:
        std::vector<Token> tokens_; ///< The complete sequence of tokens to parse.
        size_t current_ = 0;        ///< The index of the token currently being evaluated.

        /**
         * @brief Retrieves the current token without advancing the parser's state.
         * @return The current Token.
         */
        Token Peek() const;

        /**
         * @brief Consumes the current token and advances the parser's position.
         * @return The Token that was just consumed.
         */
        Token Advance();

        /**
         * @brief Checks if the parser has reached the end of the token sequence.
         * @return true if the current token is of type END_OF_FILE, false otherwise.
         */
        bool IsAtEnd() const;

        /**
         * @brief Checks if the current token matches a specific type without consuming it.
         * @param type The TokenType to check against the current token.
         * @return true if the current token matches the provided type, false otherwise.
         */
        bool Check(TokenType type) const;
        
        /**
         * @brief Validates that the current token matches an expected type, consuming it if successful.
         * @param type The TokenType expected at the current position.
         * @param message The error message to throw if the token does not match the expected type.
         * @return The consumed Token.
         * @throws std::runtime_error with the provided message if the type does not match.
         */
        Token Consume(TokenType type, const std::string& message);

        /**
         * @brief Parses a numerical value.
         * @return Pointer to a newly created NumberExpression node.
         */
        NumberExpression* ParseNumber(); 

        /**
         * @brief Parses a string literal or identifier.
         * @return Pointer to a newly created StringExpression node.
         */
        StringExpression* ParseString(); 

        /**
         * @brief Parses a 12-dimensional vector enclosed in brackets.
         * @return Pointer to a newly created CoordExpression node.
         */
        CoordExpression* ParseVector();

        /**
         * @brief Parses an ANALYZE command (either TICKER or MANUAL variants).
         * @return Pointer to a newly created AnalyzeExpression node.
         */
        AnalyzeExpression* ParseAnalyzeCommand();

        /**
         * @brief Parses a CONFIGURE command to update application paths.
         * @return Pointer to a newly created ConfigureExpression node.
         */
        Expression* ParseConfigureCommand();

        /**
         * @brief Parses a VIEW CONFIGS command.
         * @return Pointer to a newly created ViewConfigExpression node.
         */
        Expression* ParseViewConfigCommand();

        /**
         * @brief Parses a CLEAR command to clear the terminal.
         * @return Pointer to a newly created ClearExpression node.
         */
        ClearExpression* ParseClearCommand();

        /**
         * @brief Parses a QUIT command to exit the application.
         * @return Pointer to a newly created QuitExpression node.
         */
        QuitExpression* ParseQuitCommand();

        /**
         * @brief Parses a PROFILE command (ADD, REMOVE, VIEW, or VIEW ALL variants).
         * @return Pointer to the appropriate profile-related Expression node.
         */
        Expression* ParseProfileCommand();

        bool configure_mode_; ///< Flag indicating if the parser is running in strict configuration mode.

        /**
         * @brief Determines the next appropriate parsing rule based on the current token.
         * @return Pointer to the next evaluated Expression node.
         */
        Expression* ParseNext();

    public:
        /**
         * @brief Constructs a new Parser.
         * @param tokens The vector of tokens generated by the Lexer.
         * @param config_mode If true, restricts parsing exclusively to configuration commands.
         */
        explicit Parser(const std::vector<Token>& tokens, bool config_mode = false);

        /**
         * @brief Executes the top-level parsing process.
         * 
         * Iterates through the provided token stream, recursively building the AST 
         * until the end of the file is reached.
         * 
         * @return Pointer to the root Expression node of the generated AST.
         */
        Expression* Parse(); 
};